# Generated by Django 4.2.25 on 2025-10-16 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('unique_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('encrypted_data', models.TextField()),
                ('signature', models.TextField()),
                ('hash_value', models.CharField(max_length=64)),
                ('salt', models.CharField(max_length=64)),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('algorithm', models.CharField(default='AES256-GCM', max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('SUSPENDED', 'Suspendu'), ('REVOKED', 'Révoqué'), ('EXPIRED', 'Expiré')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'qr_codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QRCodeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('template_data', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'qr_code_templates',
            },
        ),
        migrations.CreateModel(
            name='QRVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('is_valid', models.BooleanField()),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='qr_codes.qrcode')),
            ],
            options={
                'db_table': 'qr_verifications',
                'ordering': ['-verified_at'],
                'indexes': [models.Index(fields=['qr_code', 'verified_at'], name='qr_verifica_qr_code_e754d9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['unique_code'], name='qr_codes_unique__76c2fd_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['status'], name='qr_codes_status_9bd52c_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['expires_at'], name='qr_codes_expires_a30ec8_idx'),
        ),
    ]
